version: 2.1
jobs:
  build:
    - image: circleci/python:3.6.2
    executor: python/default
  steps:
    - checkout
    - run:
        command: |
          python3 -m venv venv
          . venv/bin/activate
          pip install pytest
          pytest tests
